num1 = int(input("Enter the first number : "))
num2 = int(input("Enter the second number : "))
print("\nThe addition of ",num1,"and",num2," is :",num1+num2)
print("The subtraction of ",num1,"and",num2," is :",num1-num2)
print("The multiplication of ",num1,"and",num2," is :",num1*num2)
print("The division of ",num1,"and",num2," is :",num1/num2)
print("The modulus of ",num1,"and",num2," is :",num1%num2)